@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Dec 02 23:35:56 +0800 2025
REM SW Build 5239630 on Fri Nov 08 22:35:27 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_ctrl_top_behav -key {Behavioral:sim_1:Functional:tb_ctrl_top} -tclbatch tb_ctrl_top.tcl -view C:/Users/dyf31/Desktop/DYF/ASIC/8Bit/tb_multi_array_behav.wcfg -view C:/Users/dyf31/Desktop/DYF/ASIC/8Bit/tb_top_truncrelu_behav.wcfg -view C:/Users/dyf31/Desktop/DYF/ASIC/8Bit/tb_controller.wcfg -log simulate.log"
call xsim  tb_ctrl_top_behav -key {Behavioral:sim_1:Functional:tb_ctrl_top} -tclbatch tb_ctrl_top.tcl -view C:/Users/dyf31/Desktop/DYF/ASIC/8Bit/tb_multi_array_behav.wcfg -view C:/Users/dyf31/Desktop/DYF/ASIC/8Bit/tb_top_truncrelu_behav.wcfg -view C:/Users/dyf31/Desktop/DYF/ASIC/8Bit/tb_controller.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
